# Generated by Django 6.0.5 on 2026-06-15 06:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_diaryentry_notification_postimage_userrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PDS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(blank=True, max_length=100)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('name_extension', models.CharField(blank=True, max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('place_of_birth', models.CharField(blank=True, max_length=200)),
                ('sex', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('civil_status', models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('widowed', 'Widowed'), ('separated', 'Separated'), ('other', 'Other')], max_length=20)),
                ('height', models.CharField(blank=True, max_length=20)),
                ('weight', models.CharField(blank=True, max_length=20)),
                ('blood_type', models.CharField(blank=True, max_length=5)),
                ('citizenship', models.CharField(blank=True, choices=[('filipino', 'Filipino'), ('dual', 'Dual Citizenship')], max_length=20)),
                ('res_house_no', models.CharField(blank=True, max_length=100)),
                ('res_street', models.CharField(blank=True, max_length=100)),
                ('res_subdivision', models.CharField(blank=True, max_length=100)),
                ('res_barangay', models.CharField(blank=True, max_length=100)),
                ('res_city', models.CharField(blank=True, max_length=100)),
                ('res_province', models.CharField(blank=True, max_length=100)),
                ('res_zip', models.CharField(blank=True, max_length=10)),
                ('perm_house_no', models.CharField(blank=True, max_length=100)),
                ('perm_street', models.CharField(blank=True, max_length=100)),
                ('perm_subdivision', models.CharField(blank=True, max_length=100)),
                ('perm_barangay', models.CharField(blank=True, max_length=100)),
                ('perm_city', models.CharField(blank=True, max_length=100)),
                ('perm_province', models.CharField(blank=True, max_length=100)),
                ('perm_zip', models.CharField(blank=True, max_length=10)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('mobile', models.CharField(blank=True, max_length=30)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('emergency_name', models.CharField(blank=True, max_length=200)),
                ('emergency_relationship', models.CharField(blank=True, max_length=100)),
                ('emergency_address', models.TextField(blank=True)),
                ('emergency_phone', models.CharField(blank=True, max_length=30)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pds', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('elementary', 'Elementary'), ('secondary', 'Secondary'), ('vocational', 'Vocational'), ('college', 'College')], max_length=20)),
                ('school', models.CharField(blank=True, max_length=200)),
                ('course', models.CharField(blank=True, max_length=200)),
                ('year_graduated', models.CharField(blank=True, max_length=10)),
                ('pds', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='myapp.pds')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('pds', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='myapp.pds')),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=200)),
                ('position', models.CharField(blank=True, max_length=200)),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('pds', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experience', to='myapp.pds')),
            ],
        ),
    ]
