# Generated by Django 6.0.5 on 2026-06-17 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_pds_education_skill_workexperience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pds',
            name='emergency_address',
        ),
        migrations.RemoveField(
            model_name='pds',
            name='emergency_name',
        ),
        migrations.RemoveField(
            model_name='pds',
            name='emergency_phone',
        ),
        migrations.RemoveField(
            model_name='pds',
            name='emergency_relationship',
        ),
        migrations.AddField(
            model_name='education',
            name='edu_status',
            field=models.CharField(blank=True, choices=[('graduated', 'Graduated'), ('undergraduate', 'Undergraduate'), ('ongoing', 'Ongoing')], max_length=20),
        ),
        migrations.AddField(
            model_name='pds',
            name='age',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('technical', 'Technical'), ('soft', 'Soft Skills'), ('language', 'Language'), ('tools', 'Tools & Software'), ('professional', 'Professional'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
