# Generated by Django 6.0.5 on 2026-06-23 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_remove_pds_emergency_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostalCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('psgc_city_code', models.CharField(db_index=True, help_text="PSGC code for the city/municipality, e.g. '031403000'", max_length=10, unique=True)),
                ('city_name', models.CharField(max_length=255)),
                ('province_name', models.CharField(blank=True, default='', max_length=255)),
                ('zip_code', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Postal/ZIP Code',
                'verbose_name_plural': 'Postal/ZIP Codes',
                'ordering': ['province_name', 'city_name'],
            },
        ),
    ]
